// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.Test;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Test_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Test.entityManager;
    
    public static final EntityManager Test.entityManager() {
        EntityManager em = new Test().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Test.countTests() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Test o", Long.class).getSingleResult();
    }
    
    public static List<Test> Test.findAllTests() {
        return entityManager().createQuery("SELECT o FROM Test o", Test.class).getResultList();
    }
    
    public static Test Test.findTest(Integer id) {
        if (id == null) return null;
        return entityManager().find(Test.class, id);
    }
    
    public static List<Test> Test.findTestEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Test o", Test.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Test.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Test.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Test attached = Test.findTest(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Test.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Test.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Test Test.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Test merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
