// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.Test;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect Test_Roo_Jpa_Entity {
    
    declare @type: Test: @Entity;
    
    declare @type: Test: @Table(schema = "PUBLIC", name = "TEST");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ID")
    private Integer Test.id;
    
    public Integer Test.getId() {
        return this.id;
    }
    
    public void Test.setId(Integer id) {
        this.id = id;
    }
    
}
